ecomprj/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    # HOMEPAGE
    path('', views.index, name="index"),
    path("products/", views.product_list, name="product-list"),
    path("product/<pid>/", views.product_detail, name="product-detail"),

    # CATEGORY VIEW
    path("category/", views.category_list, name="category-list"),
    path("category/<cid>/", views.category_product_list, name="category-product-list"),

    # VENDOR VIEW
    path("vendors/", views.vendor_list, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail, name="vendor-detail"),

    #Tags
    path("product/tags/<slug:tag_slug>/",views.tag_list, name="tag-list"),

    #Review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    # SEARCH
    path("search/", views.search_view, name="search"),

    # Filter
    path("filter-products/", views.filter_products, name="filter-products"),

    #Add to Cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    #Cart List
    path("cart/", views.cart_view, name="cart"),
    #Delete from Cart
    path("delete-from-cart/", views.delete_from_cart_view, name="delete-from-cart"),
    #Update cart view
    path("update-cart/", views.update_cart_view, name="update-cart"),

    #CheckOut!
    path("checkout/<oid>/", views.checkout_view, name="checkout"),

    # #Paypal
    # path("paypal/", include('paypal.standard.ipn.urls'), name="paypal-ipn"),
    path("payment-successfull/<oid>/", views.payment_successfull, name="payment-successfull"),
    path("payment-failed/", views.payment_failed, name="payment-failed"),

    #Dashboard
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    #order detail
    path("dashboard/order/<int:id>/", views.order_products, name="order-detail"),

    #Make Default
    path("make-default-address/", views.make_default_address, name="make-default-address"),

    #Wishlist
    path("wishlist/", views.wishlist_view, name="wishlist"),

    #Add to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    #Remove from wishlist
    path("remove-from-wishlist/", views.remove_from_wishlist, name="remove-from-wishlist"),

    #Contact US
    path("contact-us/", views.contact_us, name="contact"),
    path("ajax-contact-us", views.ajax_contact_us, name="ajax_contact_us"),

    #new paths
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),
    path("api/create_checkout_session/<oid>/", views.create_checkout_session, name="create-checkout-session"),

    #About us
    path("about-us/", views.about_us, name="about-us"),

    #Purchase Guide
    path("purchase-guide/", views.purchase_guide, name="purchase-guide"),
    #Privacy Policy
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
    #Terms of Services
    path("terms-of-service/", views.terms_of_service, name="terms-of-service"),
    ]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path("user/", include('userauths.urls', namespace='userauths')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include('useradmin.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/core/forms.py
from django import forms
from .models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Add a Review"}))

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]


ecomprj/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Coupon, Category, Vendor, CartOrder, CartOrderItems, WishList, ProductReview, Address, ProductImages
from django.db.models import Count,Avg
from taggit.models import Tag
from .forms import ProductReviewForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from userauths.models import ContactUs
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from userauths.models import Profile
from django.core import serializers
import calendar
from django.db.models.functions import ExtractMonth
import stripe



def index(request):
    # product = Product.objects.all().order_by("-id")
    product = Product.objects.filter(product_status = "published", featured = True).order_by("-id")
    deals_of_the_day =Product.objects.filter(deal_of_the_day=True)
    context = {
        "deals_of_the_day" : deals_of_the_day,
        "product" : product,
    }
    return render(request, 'core/index.html', context)

def product_list(request):
    product = Product.objects.filter(product_status = "published")
    context = {
        "products" : product,
    }
    return render(request, 'core/product-list.html', context)

def category_list(request):
    categories = Category.objects.all()
    # categories = Category.objects.all().annotate(product_count = Count("products"))
    context = {
        "categories" : categories,
    }
    return render(request, "core/category-list.html", context)

def category_product_list(request, cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(product_status = "published", category = category)

    context = {
        "category" : category,
        "products" : products,
    }
    return render(request, "core/category-product-list.html", context)

def vendor_list(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors" : vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status = "published", vendor=vendor)
    context = {
        "vendor" : vendor,
        "products" : products,
    }
    return render(request, "core/vendor-detail.html", context)

def product_detail(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category = product.category).exclude(pid=pid)

    # Getting all reviews for a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Average Ratings
    average_ratings = ProductReview.objects.filter(product=product).aggregate(rating = Avg("rating"))

    # Forms
    review_form = ProductReviewForm()

    p_image = product.p_images.all()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "product" : product,
        "make_review" : make_review,
        "p_image" : p_image,
        "average_ratings" : average_ratings,
        "reviews" : reviews,
        "products" : products,
        "review_form" : review_form,
    }
    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status = "published")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in = [tag])

    context = {
        "products" : products,
        "tag" : tag,
    }
    return render(request, "core/tags.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST["review"],
        rating = request.POST["rating"],
    )

    context = {
        "user" : user.username,
        "review" : request.POST["review"],
        "rating" : request.POST["rating"],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating = Avg("rating"))

    return JsonResponse(
        {
            'bool' : True,
            'context' : context,
            'average_reviews' : average_reviews
        }
    )

def search_view(request):

    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains = query).order_by("-date")

    context = {
        "products" : products,
        "query" : query,
    }
    return render(request, "core/search.html", context)

def filter_products(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    try:
        min_price = float(request.GET.get("min_price", 0))
        max_price = float(request.GET.get("max_price", 999999))
    except ValueError:
        min_price = 0
        max_price = 999999

    # print(f"Received categories: {categories}")
    # print(f"Received vendors: {vendors}")
    # print(f"Received min_price: {min_price}")
    # print(f"Received max_price: {max_price}")

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    if min_price is not None and max_price is not None:
        products = products.filter(price__gte=min_price, price__lte=max_price)

    if categories:
        products = products.filter(category__id__in=categories)

    if vendors:
        products = products.filter(vendor__id__in=vendors)

    print("Final QuerySet:", products.query)
    data = render_to_string("core/async/product-list.html", {"products": products})

    return JsonResponse({"data": data})



def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        "title" : request.GET['title'],
        "quantity" : request.GET['quantity'],
        "price" : request.GET['price'],
        "image" : request.GET['image'],
        "pid" : request.GET['pid'],
    }

    if "cart_data_obj" in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]["quantity"] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data": request.session['cart_data_obj'], "totalCartItems": len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total += int(item['quantity']) * float(item['price'])
        return render(request, "core/cart.html", {"cart_data": request.session['cart_data_obj'], "totalCartItems": len(request.session['cart_data_obj']), "cart_total" : cart_total})
    else:
        messages.warning(request,"Cart is Empty!")
        return redirect("core:index")


def delete_from_cart_view(request):
    product_id = str(request.GET.get("id"))

    if "cart_data_obj" in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del cart_data[product_id]
            request.session['cart_data_obj'] = cart_data
    
    # Calculate the cart total
    cart_total = sum(int(item['quantity']) * float(item['price']) for item in request.session['cart_data_obj'].values())
    
    context = render_to_string("core/async/cart-list.html", {
        "cart_data": request.session['cart_data_obj'],
        "totalCartItems": len(request.session['cart_data_obj']),
        "cart_total": cart_total
    })
    
    return JsonResponse({"data": context, "totalCartItems": len(request.session['cart_data_obj'])})


def update_cart_view(request):
    product_id = str(request.GET.get("id"))
    product_quantity = request.GET['product_quantity']

    if "cart_data_obj" in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[product_id]['quantity'] = product_quantity
            request.session['cart_data_obj'] = cart_data
    
    # Calculate the cart total
    cart_total = sum(int(item['quantity']) * float(item['price']) for item in request.session['cart_data_obj'].values())
    
    context = render_to_string("core/async/cart-list.html", {
        "cart_data": request.session['cart_data_obj'],
        "totalCartItems": len(request.session['cart_data_obj']),
        "cart_total": cart_total
    })
    
    return JsonResponse({"data": context, "totalCartItems": len(request.session['cart_data_obj'])})

@login_required
def save_checkout_info(request):
    cart_total = 0
    total_amount = 0

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        city = request.POST.get("city")
        state = request.POST.get("state")
        country = request.POST.get("country")


ecomprj/templates/core/async/cart-list.html

<main class="main" id="cart-list">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url "core:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Cart
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Cart</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{totalCartItems}}</span> products in your cart</h6>
                </div>
            </div>
        </div>
        <form action="{% url 'core:save-checkout-info' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col">Refresh</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                    <tr class="pt-30">
                                        <td class="image product-thumbnail pt-40"><img src="{{item.image}}" alt="#"></td>
                                        <td class="product-des product-name">
                                            <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="shop-product-right.html">{{item.title}}</a></h6>
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-body">${{item.price|floatformat:0}}</h4>
                                        </td>
                                        <td class="text-center detail-info" data-title="Stock">
                                            <div class="detail-extralink mr-15">
                                                <input type="number" class="w-25 update-product-{{product_id}}" placeholder="QtY" name="" value="{{item.quantity}}" />
                                            </div>
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-brand">${% widthratio item.price 1 item.quantity %}</h4>
                                        </td>
                                        <td class="action text-center" data-title="Remove"><button type="button" style="background: none; border: none;" class="text-body update-product" data-product="{{product_id}}"><i class="fi-rs-refresh"></i></button></td>
                                        <td class="action text-center" data-title="Remove"><button type="button" style="background: none; border: none;" class="text-body delete-product" data-product="{{product_id}}"><i class="fi-rs-trash"></i></button></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <div class="cart-action d-flex justify-content-between">
                        <a class="btn" href="{% url "core:index" %}"><i class="fi-rs-arrow-left mr-10"></i>Continue Shopping</a>
                        <a class="btn mr-10 mb-sm-15"><i class="fi-rs-refresh mr-10"></i>Update Cart</a>
                    </div>
                    <div class="row mt-50">
                        <div class="col-lg-12">
                            <div class="p-40">
                                <h4 class="mb-10">Bio Data</h4>
                                <form>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="full-name">Full Name</label>
                                                <input type="text" class="form-control" id="full-name" name="full_name" value="" placeholder="Full Name">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="email">Email</label>
                                                <input type="email" class="form-control" id="email" name="email" value="" placeholder="Email">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="mobile">Mobile</label>
                                                <input type="text" class="form-control" id="phone" name="phone" vlaue="" placeholder="Mobile">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="address">Address</label>
                                                <input type="text" class="form-control" id="address" name="address" vlaue="" placeholder="Address">
                                            </div>
                                        </div>
                                    </div>
                                    <h4 class="mb-10">Shipping Details</h4>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="shipping-address">Address</label>
                                                <input type="text" class="form-control" id="shipping-address" name="address" vlaue="" placeholder="Address">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="city">City</label>
                                                <input type="text" class="form-control" name="city" vlaue="" id="city" placeholder="City">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="state">State</label>
                                                <input type="text" class="form-control" id="state" name="state" value="" placeholder="State">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="country">Country</label> 
                                                <input type="text" class="form-control" id="country" name="country" vlaue="" placeholder="Country">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Tax</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Shipping</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Discount</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Total</p>
                                <p>${{cart_total}}</p>
                            </div>
                        </div>
                        {% if totalCartItems %}
                        <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                        {% endif %}
                    </div>
                </div>                
            </div>
        </form>
    </div>
</main>

ecomprj/templates/core/async/product-list.html
{% load static %}
{% for p in products %}
    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
        <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".1s">
            <div class="product-img-action-wrap">
                <div class="product-img product-img-zoom">
                    <a href="{% url "core:product-detail" p.pid %}">
                        <img class="default-img" src="{{ p.image.url }}" alt="" />
                        <img class="hover-img" src="{{ p.image.url }}" alt="" />
                    </a>
                </div>
                <div class="product-action-1">
                    <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                    <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                    <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                </div>
                <div class="product-badges product-badges-position product-badges-mrg">
                    <span class="hot">-{{p.get_percentage|floatformat:0}}%</span>
                </div>
            </div>
            <div class="product-content-wrap">
                <div class="product-category">
                    <a href="shop-grid-right.html">{{p.category.title}}</a>
                </div>
                <h2><a href="{% url "core:product-detail" p.pid %}">{{p.title}}</a></h2>
                <div class="product-rate-cover">
                    <div class="product-rate d-inline-block">
                        <div class="product-rating" style="width: 90%"></div>
                    </div>
                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                </div>
                <div>
                    <span class="font-small text-muted">By <a href="vendor-details-1.html">{{p.vendor.title}}</a></span>
                </div>
                <div class="product-card-bottom">
                    <div class="product-price">
                        <span>${{p.price}}</span>
                        <span class="old-price">${{p.old_price}}</span>
                    </div>
                    <div class="add-cart">
                        <a class="add" href="shop-cart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

ecomprj/templates/core/async/wishlist-list.html

    <main class="main" id="wish-list-rem">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">{{wishlist.count}}</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in wishlist %}
                                <tr class="pt-30">
                                    <td class="image product-thumbnail pt-40"><img src="{{w.product.image.url}}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class="product-name mb-10" href="{% url "core:product-detail" w.product.pid %}">{{w.product.title|truncatechars:30}}</a></h6>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <span class="text-brand fs-1">$</span><span class="text-brand fs-1 current-product-price-{{w.product.id}}">{{w.product.price|floatformat:2}}</span>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %} </span>
                                    </td>
                                    <td class="text-right" data-title="Cart">
                                        <input type="hidden" value="1" name="" id="product-quantity" class="w-25 mb-20 product-quantity-{{w.product.id}}">
                                        <input type="hidden" name="" id="" class="product-pid-{{w.product.id}}" value="{{w.product.pid}}">
                                        <input type="hidden" name="" id="" class="product-image-{{w.product.id}}" value="{{w.product.image.url}}">
                                        <input type="hidden" class="product-id-{{w.product.id}}" value="{{ w.product.id }}" name="" id="">
                                        <input type="hidden" class="product-title-{{w.product.id}}" value="{{w.product.title }}" name="" id="">

                                        <button class="btn btn-sm add add-to-cart-btn b-none" data-index="{{ w.product.id }}">Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <button style="border:none; background:none;" data-wishlist="{{w.id}}" class="text-body remove-from-wishlist"><i class="fi-rs-trash"></i></button>
                                    </td>
                                </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="1">
                                            <h5>Nothing in Wishlist</h5>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>