ecomprj/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    # HOMEPAGE
    path('', views.index, name="index"),
    path("products/", views.product_list, name="product-list"),
    path("product/<pid>/", views.product_detail, name="product-detail"),

    # CATEGORY VIEW
    path("category/", views.category_list, name="category-list"),
    path("category/<cid>/", views.category_product_list, name="category-product-list"),

    # VENDOR VIEW
    path("vendors/", views.vendor_list, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail, name="vendor-detail"),

    #Tags
    path("product/tags/<slug:tag_slug>/",views.tag_list, name="tag-list"),

    #Review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    # SEARCH
    path("search/", views.search_view, name="search"),

    # Filter
    path("filter-products/", views.filter_products, name="filter-products"),

    #Add to Cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    #Cart List
    path("cart/", views.cart_view, name="cart"),
    #Delete from Cart
    path("delete-from-cart/", views.delete_from_cart_view, name="delete-from-cart"),
    #Update cart view
    path("update-cart/", views.update_cart_view, name="update-cart"),

    #CheckOut!
    path("checkout/<oid>/", views.checkout_view, name="checkout"),

    # #Paypal
    # path("paypal/", include('paypal.standard.ipn.urls'), name="paypal-ipn"),
    path("payment-successfull/<oid>/", views.payment_successfull, name="payment-successfull"),
    path("payment-failed/", views.payment_failed, name="payment-failed"),

    #Dashboard
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    #order detail
    path("dashboard/order/<int:id>/", views.order_products, name="order-detail"),

    #Make Default
    path("make-default-address/", views.make_default_address, name="make-default-address"),

    #Wishlist
    path("wishlist/", views.wishlist_view, name="wishlist"),

    #Add to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    #Remove from wishlist
    path("remove-from-wishlist/", views.remove_from_wishlist, name="remove-from-wishlist"),

    #Contact US
    path("contact-us/", views.contact_us, name="contact"),
    path("ajax-contact-us", views.ajax_contact_us, name="ajax_contact_us"),

    #new paths
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),
    path("api/create_checkout_session/<oid>/", views.create_checkout_session, name="create-checkout-session"),

    #About us
    path("about-us/", views.about_us, name="about-us"),

    #Purchase Guide
    path("purchase-guide/", views.purchase_guide, name="purchase-guide"),
    #Privacy Policy
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
    #Terms of Services
    path("terms-of-service/", views.terms_of_service, name="terms-of-service"),
    ]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path("user/", include('userauths.urls', namespace='userauths')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include('useradmin.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/core/forms.py
from django import forms
from .models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Add a Review"}))

    class Meta:
        model = ProductReview
        fields = ["review", "rating"]


ecomprj/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Coupon, Category, Vendor, CartOrder, CartOrderItems, WishList, ProductReview, Address, ProductImages
from django.db.models import Count,Avg
from taggit.models import Tag
from .forms import ProductReviewForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from userauths.models import ContactUs
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from userauths.models import Profile
from django.core import serializers
import calendar
from django.db.models.functions import ExtractMonth
import stripe



def index(request):
    # product = Product.objects.all().order_by("-id")
    product = Product.objects.filter(product_status = "published", featured = True).order_by("-id")
    deals_of_the_day =Product.objects.filter(deal_of_the_day=True)
    context = {
        "deals_of_the_day" : deals_of_the_day,
        "product" : product,
    }
    return render(request, 'core/index.html', context)

def product_list(request):
    product = Product.objects.filter(product_status = "published")
    context = {
        "products" : product,
    }
    return render(request, 'core/product-list.html', context)

def category_list(request):
    categories = Category.objects.all()
    # categories = Category.objects.all().annotate(product_count = Count("products"))
    context = {
        "categories" : categories,
    }
    return render(request, "core/category-list.html", context)

def category_product_list(request, cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(product_status = "published", category = category)

    context = {
        "category" : category,
        "products" : products,
    }
    return render(request, "core/category-product-list.html", context)

def vendor_list(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors" : vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status = "published", vendor=vendor)
    context = {
        "vendor" : vendor,
        "products" : products,
    }
    return render(request, "core/vendor-detail.html", context)

def product_detail(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category = product.category).exclude(pid=pid)

    # Getting all reviews for a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Average Ratings
    average_ratings = ProductReview.objects.filter(product=product).aggregate(rating = Avg("rating"))

    # Forms
    review_form = ProductReviewForm()

    p_image = product.p_images.all()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "product" : product,
        "make_review" : make_review,
        "p_image" : p_image,
        "average_ratings" : average_ratings,
        "reviews" : reviews,
        "products" : products,
        "review_form" : review_form,
    }
    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status = "published")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in = [tag])

    context = {
        "products" : products,
        "tag" : tag,
    }
    return render(request, "core/tags.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST["review"],
        rating = request.POST["rating"],
    )

    context = {
        "user" : user.username,
        "review" : request.POST["review"],
        "rating" : request.POST["rating"],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating = Avg("rating"))

    return JsonResponse(
        {
            'bool' : True,
            'context' : context,
            'average_reviews' : average_reviews
        }
    )

def search_view(request):

    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains = query).order_by("-date")

    context = {
        "products" : products,
        "query" : query,
    }
    return render(request, "core/search.html", context)

def filter_products(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    try:
        min_price = float(request.GET.get("min_price", 0))
        max_price = float(request.GET.get("max_price", 999999))
    except ValueError:
        min_price = 0
        max_price = 999999

    # print(f"Received categories: {categories}")
    # print(f"Received vendors: {vendors}")
    # print(f"Received min_price: {min_price}")
    # print(f"Received max_price: {max_price}")

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    if min_price is not None and max_price is not None:
        products = products.filter(price__gte=min_price, price__lte=max_price)

    if categories:
        products = products.filter(category__id__in=categories)

    if vendors:
        products = products.filter(vendor__id__in=vendors)

    print("Final QuerySet:", products.query)
    data = render_to_string("core/async/product-list.html", {"products": products})

    return JsonResponse({"data": data})



def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        "title" : request.GET['title'],
        "quantity" : request.GET['quantity'],
        "price" : request.GET['price'],
        "image" : request.GET['image'],
        "pid" : request.GET['pid'],
    }

    if "cart_data_obj" in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]["quantity"] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data": request.session['cart_data_obj'], "totalCartItems": len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total += int(item['quantity']) * float(item['price'])
        return render(request, "core/cart.html", {"cart_data": request.session['cart_data_obj'], "totalCartItems": len(request.session['cart_data_obj']), "cart_total" : cart_total})
    else:
        messages.warning(request,"Cart is Empty!")
        return redirect("core:index")


def delete_from_cart_view(request):
    product_id = str(request.GET.get("id"))

    if "cart_data_obj" in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del cart_data[product_id]
            request.session['cart_data_obj'] = cart_data
    
    # Calculate the cart total
    cart_total = sum(int(item['quantity']) * float(item['price']) for item in request.session['cart_data_obj'].values())
    
    context = render_to_string("core/async/cart-list.html", {
        "cart_data": request.session['cart_data_obj'],
        "totalCartItems": len(request.session['cart_data_obj']),
        "cart_total": cart_total
    })
    
    return JsonResponse({"data": context, "totalCartItems": len(request.session['cart_data_obj'])})


def update_cart_view(request):
    product_id = str(request.GET.get("id"))
    product_quantity = request.GET['product_quantity']

    if "cart_data_obj" in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[product_id]['quantity'] = product_quantity
            request.session['cart_data_obj'] = cart_data
    
    # Calculate the cart total
    cart_total = sum(int(item['quantity']) * float(item['price']) for item in request.session['cart_data_obj'].values())
    
    context = render_to_string("core/async/cart-list.html", {
        "cart_data": request.session['cart_data_obj'],
        "totalCartItems": len(request.session['cart_data_obj']),
        "cart_total": cart_total
    })
    
    return JsonResponse({"data": context, "totalCartItems": len(request.session['cart_data_obj'])})

@login_required
def save_checkout_info(request):
    cart_total = 0
    total_amount = 0

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        city = request.POST.get("city")
        state = request.POST.get("state")
        country = request.POST.get("country")


ecomprj/templates/core/category-product-list.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="{% url "core:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> {{category.title}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shop-product-fillter mb-50">
                            <div class="totall-product">
                                <h2>
                                    <img class="w-36px mr-10" src="{{category.image.url}}" alt="" />
                                    {{products.count}} - Item{{products.count|pluralize}} Found
                                </h2>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Featured</a></li>
                                            <li><a href="#">Newest</a></li>
                                            <li><a href="#">Most comments</a></li>
                                            <li><a href="#">Release Date</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="loop-grid">
                            <div class="row">
                                {% for p in products %}
                                    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                        <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".1s">
                                            <div class="product-img-action-wrap">
                                                <div class="product-img product-img-zoom">
                                                    <a href="{% url "core:product-detail" p.pid %}">
                                                        <img class="default-img" src="{{ p.image.url }}" alt="" />
                                                        <img class="hover-img" src="{{ p.image.url }}" alt="" />
                                                    </a>
                                                </div>
                                                <div class="product-action-1">
                                                    <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                                    <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                                                    <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                                                </div>
                                                <div class="product-badges product-badges-position product-badges-mrg">
                                                    <span class="hot">-{{p.get_percentage|floatformat:0}}%</span>
                                                </div>
                                            </div>
                                            <div class="product-content-wrap">
                                                <div class="product-category">
                                                    <a href="shop-grid-right.html">{{p.category.title}}</a>
                                                </div>
                                                <h2><a href="{% url "core:product-detail" p.pid %}">{{p.title}}</a></h2>
                                                <div class="product-rate-cover">
                                                    <div class="product-rate d-inline-block">
                                                        <div class="product-rating" style="width: 90%"></div>
                                                    </div>
                                                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                                                </div>
                                                <div>
                                                    <span class="font-small text-muted">By <a href="vendor-details-1.html">{{p.vendor.title}}</a></span>
                                                </div>
                                                <div class="product-card-bottom">
                                                    <div class="product-price">
                                                        <span>$</span> <span class="current-product-price-{{p.id}}">{{p.price}}</span>
                                                        <span class="old-price">${{p.old_price}}</span>
                                                    </div>
                                                    <div class="add-cart">
                                                        <input type="hidden" value="1" name="" id="product-quantity" class="w-25 mb-20 product-quantity-{{p.id}}">
                                                        <input type="hidden" name="" id="" class="product-pid-{{p.id}}" value="{{p.pid}}">
                                                        <input type="hidden" name="" id="" class="product-image-{{p.id}}" value="{{p.image.url}}">
                                                        <input type="hidden" class="product-id-{{p.id}}" value="{{ p.id }}" name="" id="">
                                                        <input type="hidden" class="product-title-{{p.id}}" value="{{p.title }}" name="" id="">
                                                        <button class="add add-to-cart-btn b-none" data-index="{{ p.id }}"><i class="fi-rs-shopping-cart mr-5" id="add-to-cart-btn"></i>Add </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

ecomprj/templates/core/terms-of-service.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url "core:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> Terms of Service
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="row">
                    <div class="col-xl-10 col-lg-12 m-auto">
                        <div class="row">
                            <div class="col-lg-9">
                                <div class="single-page pr-30 mb-lg-0 mb-sm-5">
                                    <div class="single-header style-2">
                                        <h2>Terms of Service</h2>
                                        <div class="entry-meta meta-1 meta-3 font-xs mt-15 mb-15">
                                            <span class="post-by">By <a href="#">Jonh</a></span>
                                            <span class="post-on has-dot">9 April 2020</span>
                                            <span class="time-reading has-dot">8 mins read</span>
                                            <span class="hit-count has-dot">29k Views</span>
                                        </div>
                                    </div>
                                    <div class="single-content mb-50">
                                        <p>Please read these Terms of Service (“Terms”, “Terms of Service”) carefully before using the https://Evara.com website (the “Service”) operated by Evara (“us”, “we”, or “our”).</p>
                                        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
                                        <p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>
                                        <h4>Rights & restrictions</h4>
                                        <ol>
                                            <li>Members must be at least 18 years of age.</li>
                                            <li>Members are granted a time-limited, non-exclusive, revocable, nontransferable, and non-sublicensable right to access that portion of the online course corresponding to the purchase.</li>
                                            <li>The portion of the online course corresponding to the purchase will be available to the Member as long as the course is maintained by the Company, which will be a minimum of one year after Member’s purchase.</li>
                                            <li>The videos in the course are provided as a video stream and are not downloadable.</li>
                                            <li>By agreeing to grant such access, the Company does not obligate itself to maintain the course, or to maintain it in its present form.</li>
                                        </ol>
                                        <h4>Links To Other Web Sites</h4>
                                        <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by Evara.</p>
                                        <p>Evara has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Evara shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
                                        <p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
                                        <h4>Termination</h4>
                                        <p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
                                        <p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
                                        <h4>Governing Law</h4>
                                        <p>These Terms shall be governed and construed in accordance with the laws of Viet Nam, without regard to its conflict of law provisions.</p>
                                        <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
                                        <h4>Changes</h4>
                                        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
                                        <p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
                                        <h4>Contact Us</h4>
                                        <p>If you have any questions about these Terms, please <a href="{% url "core:contact" %}">contact us</a>.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 primary-sidebar sticky-sidebar">
                                <div class="widget-area">
                                    <div class="sidebar-widget widget-category-2 mb-30">
                                        <h5 class="section-title style-1 mb-30">Category</h5>
                                        <ul>
                                            {% for c in categories %}
                                            <li>
                                                <a href="{% url "core:category-product-list" c.cid %}"> <img src="{{c.image.url}}" alt="" />{{c.title|title|truncatechars:30}}</a><span class="count">{{c.category.all.count}}</span>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="banner-img wow fadeIn mb-40 animated d-lg-block d-none">
                                        <img src="{% static 'assets/imgs/banner/banner-11.png' %}" alt="" />
                                        <div class="banner-text">
                                            <span>Oganic</span>
                                            <h4>
                                                Save 17% <br />
                                                on <span class="text-brand">Oganic</span><br />
                                                Juice
                                            </h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}