ecomprj/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    # HOMEPAGE
    path('', views.index, name="index"),
    path("products/", views.product_list, name="product-list"),
    path("product/<pid>/", views.product_detail, name="product-detail"),

    # CATEGORY VIEW
    path("category/", views.category_list, name="category-list"),
    path("category/<cid>/", views.category_product_list, name="category-product-list"),

    # VENDOR VIEW
    path("vendors/", views.vendor_list, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail, name="vendor-detail"),

    #Tags
    path("product/tags/<slug:tag_slug>/",views.tag_list, name="tag-list"),

    #Review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    # SEARCH
    path("search/", views.search_view, name="search"),

    # Filter
    path("filter-products/", views.filter_products, name="filter-products"),

    #Add to Cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    #Cart List
    path("cart/", views.cart_view, name="cart"),
    #Delete from Cart
    path("delete-from-cart/", views.delete_from_cart_view, name="delete-from-cart"),
    #Update cart view
    path("update-cart/", views.update_cart_view, name="update-cart"),

    #CheckOut!
    path("checkout/<oid>/", views.checkout_view, name="checkout"),

    # #Paypal
    # path("paypal/", include('paypal.standard.ipn.urls'), name="paypal-ipn"),
    path("payment-successfull/<oid>/", views.payment_successfull, name="payment-successfull"),
    path("payment-failed/", views.payment_failed, name="payment-failed"),

    #Dashboard
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    #order detail
    path("dashboard/order/<int:id>/", views.order_products, name="order-detail"),

    #Make Default
    path("make-default-address/", views.make_default_address, name="make-default-address"),

    #Wishlist
    path("wishlist/", views.wishlist_view, name="wishlist"),

    #Add to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    #Remove from wishlist
    path("remove-from-wishlist/", views.remove_from_wishlist, name="remove-from-wishlist"),

    #Contact US
    path("contact-us/", views.contact_us, name="contact"),
    path("ajax-contact-us", views.ajax_contact_us, name="ajax_contact_us"),

    #new paths
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),
    path("api/create_checkout_session/<oid>/", views.create_checkout_session, name="create-checkout-session"),

    #About us
    path("about-us/", views.about_us, name="about-us"),

    #Purchase Guide
    path("purchase-guide/", views.purchase_guide, name="purchase-guide"),
    #Privacy Policy
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
    #Terms of Services
    path("terms-of-service/", views.terms_of_service, name="terms-of-service"),
    ]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path("user/", include('userauths.urls', namespace='userauths')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include('useradmin.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/useradmin/urls.py
from django.urls import path
from . import views

app_name = "useradmin"

urlpatterns = [
    path("dashboard/", views.dashboard, name="vendor-dashboard"),
    path("products/", views.products, name="products"),
    path("add-product/", views.add_product, name="add-product"),
    path("edit-product/<pid>/", views.edit_product, name="edit-product"),
    path("delete-product/<pid>/", views.delete_product, name="delete-product"),
    path("orders-list/", views.orders_list, name="orders-list"),
    path("order-detail/<oid>/", views.orders_detail, name="order-detail"),
    path("change-product-status/<oid>/", views.change_product_status, name="change-product-status"),
    path("shop-page/", views.shop_page, name="shop-page"),
    path("reviews/", views.reviews, name="reviews"),
    path("settings/", views.settings, name="settings"),
    path("change-password/", views.change_password, name="change-password"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

ecomprj/useradmin/models.py
from django.db import models

# Create your models here.

ecomprj/useradmin/forms.py
from django import forms
from core.models import Product,Category

class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Enter Product Title", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"Enter Product Description", "class":"form-control"}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={"placeholder":"$New Price", "class":"form-control"}))
    old_price = forms.DecimalField(widget=forms.NumberInput(attrs={"placeholder":"$Old Price", "class":"form-control"}))
    specifications = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Product Specifications if Any", "class":"form-control"}))
    stock_count = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"How many in Stock?", "class":"form-control"}))
    life = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Life of the Product", "class":"form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={"placeholder":"e.g: 2024-08-09", "class":"form-control", "type": "datetime-local"}),input_formats=["%Y-%m-%d"])
    tags = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Enter Tags separated by commas", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Product Type, e.g. Organic", "class":"form-control"}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={"class":"form-control"}))
    digital = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={"class":"form-check-input"}))
    
    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'specifications',
            'stock_count',
            'life',
            'mfd',
            'digital',
            'tags',
            'type',
            'category'
        ]

ecomprj/useradmin/views.py
from django.shortcuts import render, redirect
from core.models import CartOrder, Product, Category, CartOrderItems, ProductReview
from userauths.models import Profile
from django.db.models import Sum
from userauths.models import User
from .forms import AddProductForm
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login, authenticate, logout
from .decorators import admin_required
import datetime
# Create your views here.

@admin_required
def dashboard(request):
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_orders_count = CartOrder.objects.all()
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    new_customers = User.objects.all().order_by("-id")
    latest_orders = CartOrder.objects.all().order_by("-id")

    this_month = datetime.datetime.now().month

    monthly_revenue = CartOrder.objects.filter(order_date__month=this_month).aggregate(price=Sum("price"))

    context = {
        'revenue': revenue,
        'total_orders_count': total_orders_count,
        'all_products': all_products,
        'all_categories': all_categories,
        'new_customers': new_customers,
        'latest_orders': latest_orders,
        'monthly_revenue': monthly_revenue,
    }

    return render(request, "useradmin/dashboard.html", context)

@admin_required
def products(request):
    all_products = Product.objects.all().order_by("-id")
    all_categories = Category.objects.all()

    context = {
        'all_products': all_products,
        'all_categories': all_categories,
    }

    return render(request, "useradmin/products.html", context)

@admin_required
def add_product(request):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                new_form = form.save(commit=False)
                new_form.user = request.user
                new_form.save()
                return redirect("useradmin:products")
            except ValueError as e:
                print("Form save error:", e)
                print("Form errors:", form.errors)
                # Optionally, add a message to the context to display to the user
        else:
            print("Form is not valid:", form.errors)
    else:
        form = AddProductForm()

    context = {
        'form': form
    }

    return render(request, "useradmin/add-product.html", context)

@admin_required
def edit_product(request, pid):
    product = Product.objects.get(pid=pid)
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect("useradmin:edit-product", product.pid)
    else:
        form = AddProductForm(instance=product)

    context = {
        'form': form,
        'product' : product,
    }

    return render(request, "useradmin/edit-product.html", context)

@admin_required
def delete_product(request,pid):
    product = Product.objects.get(pid=pid)
    product.delete()
    return redirect("useradmin:products")

@admin_required
def orders_list(request):
    orders = CartOrder.objects.all()
    context = {
        "orders" : orders
    }
    return render(request, "useradmin/orders-list.html", context)

@admin_required
def orders_detail(request, oid):
    order = CartOrder.objects.get(oid=oid)
    order_items = CartOrderItems.objects.filter(order = order)

    context = {
        "order" : order,
        "order_items" : order_items
    }
    return render(request, "useradmin/order_detail.html", context)

@admin_required
@csrf_exempt
def change_product_status(request, oid):
    order = CartOrder.objects.get(oid=oid)
    if request.method == "POST":
        status = request.POST.get("status")
        print("Status  ========= >> ", status)
        order.product_status = status
        order.save()
        messages.success(request, f"Status changed to {status}")
    
    return redirect("useradmin:order-detail", order.oid)

@admin_required
def shop_page(request):
    products = Product.objects.all()
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_sales = CartOrderItems.objects.filter(order__paid_status = True).aggregate(qty=Sum("qty"))

    context = {
        "products" : products,
        "revenue" : revenue,
        "total_sales" : total_sales
    }

    return render(request, "useradmin/shop-page.html", context)

@admin_required
def reviews(request):
    reviews = ProductReview.objects.all()
    context = {
        "reviews" : reviews,
    }
    return render(request, "useradmin/reviews.html", context)

@admin_required
def settings(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        image = request.FILES.get("image")
        full_name = request.POST.get("full_name")
        phone = request.POST.get("phone")
        bio = request.POST.get("bio")
        address = request.POST.get("address")
        country = request.POST.get("country")

        if image != None:
            profile.image = image

        profile.full_name = full_name
        profile.phone = phone
        profile.bio = bio
        profile.address = address
        profile.country = country

        profile.save()
        messages.success(request, "Profile Successfully Updated!")
        return redirect("useradmin:settings")
    
    context = {
        "profile" : profile
    }

    return render(request, "useradmin/settings.html", context)


@admin_required
def change_password(request):
    user = request.user

    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        if new_password != confirm_password:
            messages.error(request, "Password Miss-Matched!!")
            return redirect("useradmin:change-password")
        
        if check_password(old_password, user.password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password Changed Successfully")
            return redirect("useradmin:login")
        else:
            messages.error(request, "Old Password is not correct")
            return redirect("useradmin:change-password")
    return render(request, "useradmin/change-password.html")


def login_view(request):
    if request.user.is_authenticated:
        return redirect("useradmin:vendor-dashboard")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email = email)
            
            user = authenticate(request, email = email, password = password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are successfully logged In!")
                return redirect("useradmin:vendor-dashboard")
            else:
                messages.error(request, "User doesn't exist, Please Sign-Up")

        except:
            messages.error(request, f"User with {email} doesn't exist")

    return render(request, "useradmin/login.html")

def logout_view(request):
    logout(request)
    messages.success(request,"Logged Out Successfully!")
    return redirect("useradmin:login")

ecomprj/templates/useradmin/login.html
{% extends "useradmin/base.html" %}    
    {% load static %}
        {% block content %}
            <section class="content-main mt-80 mb-80">
                <div class="card mx-auto card-login">
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}">
                                    <strong>{{ message }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <h4 class="card-title mb-4">Sign in</h4>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <input class="form-control" name="email" placeholder="Username or email" type="text" required />
                            </div>
                            <!-- form-group// -->
                            <div class="mb-3">
                                <input class="form-control" name="password" placeholder="Password" type="password" required />
                            </div>
                            <!-- form-group// -->
                            <div class="mb-3">
                                {% comment %} <a href="#" class="float-end font-sm text-muted">Forgot password?</a> {% endcomment %}
                                <label class="form-check">
                                    <input type="checkbox" class="form-check-input" checked="" />
                                    <span class="form-check-label">Remember</span>
                                </label>
                            </div>
                            <!-- form-group form-check .// -->
                            <div class="mb-4">
                                <button type="submit" class="btn btn-primary w-100">Login</button>
                            </div>
                            <!-- form-group// -->
                        </form>
                        <p class="text-center mb-4">Don't have account? <a href="#">Sign up</a></p>
                    </div>
                </div>
            </section>
        {% endblock content %}

ecomprj/templates/useradmin/order_detail.html
{% extends "useradmin/base.html" %}    
    {% load static %}
        {% block content %}  
            <section class="content-main">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="content-header">
                    <div>
                        <h2 class="content-title card-title">Order detail</h2>
                        <p>Details for Order ID: {{order.oid}}</p>
                    </div>
                </div>
                <div class="card">
                    <header class="card-header">
                        <div class="row align-items-center">
                            <div class="col-lg-6 col-md-6 mb-lg-0 mb-15">
                                <span> <i class="material-icons md-calendar_today"></i> <b>{{order.order_date}}</b> </span> <br />
                                <small class="text-muted">Order ID: {{order.oid}}</small>
                            </div>
                            <form method="POST" action="{% url 'useradmin:change-product-status' order.oid %}" class="col-lg-6 col-md-6 ms-auto text-md-end">
                                <select name="status" class="form-select d-inline-block mb-lg-0 mr-5 mw-200">
                                    <option value="processing">Change status</option>
                                    <option value="processing">Processing</option>
                                    <option value="shipped">Shipped</option>
                                    <option value="delivered">Delivered</option>
                                </select>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                        </div>
                    </header>
                    <!-- card-header end// -->
                    <div class="card-body">
                        <div class="row mb-50 mt-20 order-info-wrap">
                            <div class="col-md-4">
                                <article class="icontext align-items-start">
                                    <span class="icon icon-sm rounded-circle bg-primary-light">
                                        <i class="text-primary material-icons md-person"></i>
                                    </span>
                                    <div class="text">
                                        <h6 class="mb-1">Customer</h6>
                                        <p class="mb-1">
                                            {{order.full_name}} <br />
                                            {{order.email}} <br />
                                            {{order.phone}}
                                        </p>
                                        {% comment %} <a href="#">View profile</a> {% endcomment %}
                                    </div>
                                </article>
                            </div>
                            <!-- col// -->
                            <div class="col-md-4">
                                <article class="icontext align-items-start">
                                    <span class="icon icon-sm rounded-circle bg-primary-light">
                                        <i class="text-primary material-icons md-local_shipping"></i>
                                    </span>
                                    <div class="text">
                                        <h6 class="mb-1">Order info</h6>
                                        <p class="mb-1">
                                            Shipping: {{order.shipping_method}} <br />
                                            Order Id: {{order.oid}} <br />
                                            Order status: {{order.product_status|title}} <br />
                                            Payment Status: {% if order.paid_status == True %} Paid {% else %} Not Paid {% endif %}
                                        </p>
                                    </div>
                                </article>
                            </div>
                            <!-- col// -->
                            <div class="col-md-4">
                                <article class="icontext align-items-start">
                                    <span class="icon icon-sm rounded-circle bg-primary-light">
                                        <i class="text-primary material-icons md-place"></i>
                                    </span>
                                    <div class="text">
                                        <h6 class="mb-1">Deliver to</h6>
                                        <p class="mb-1">
                                            Address : {{order.address}} <br />
                                            City : {{order.city}}<br />
                                            state : {{order.state}}<br />
                                            Country : {{order.country}}<br />
                                        </p>
                                    </div>
                                </article>
                            </div>
                            <!-- col// -->
                        </div>
                        <!-- row // -->
                        <div class="row">
                            <div class="col-lg-11">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th width="40%">Product</th>
                                                <th width="20%">Unit Price</th>
                                                <th width="20%">Quantity</th>
                                                <th width="20%" class="text-end">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for o in order_items %}
                                            <tr>
                                                <td>
                                                    <a class="itemside" href="#">
                                                        <div class="left">
                                                            <img src="{{o.image}}" width="40" height="40" class="img-xs" alt="Item" />
                                                        </div>
                                                        <div class="info">{{o.item}}</div>
                                                    </a>
                                                </td>
                                                <td>${{o.price}}</td>
                                                <td>x{{o.qty}}</td>
                                                <td class="text-end">${{o.total}}</td>
                                            </tr>
                                            {% endfor %}
                                            <tr>
                                                <td colspan="4">
                                                    <article class="float-end">
                                                        <dl class="dlist">
                                                            <dt>Tax:</dt>
                                                            <dd>$0.00</dd>
                                                        </dl>
                                                        <dl class="dlist">
                                                            <dt>Shipping cost:</dt>
                                                            <dd>$0.00</dd>
                                                        </dl>
                                                        <dl class="dlist">
                                                            <dt>Discount:</dt>
                                                            <dd>${{order.saved}}</dd>
                                                        </dl>
                                                        <dl class="dlist">
                                                            <dt>Grand Total:</dt>
                                                            <dd><b class="h5">${{order.price}}</b></dd>
                                                        </dl>
                                                        <dl class="dlist">
                                                            <dt class="text-muted">Status:</dt>
                                                            <dd>
                                                                <span class="badge rounded-pill alert-success text-success">{% if order.paid_status == True %}Payment Done {% else %} Not Paid{% endif %}</span>
                                                            </dd>
                                                        </dl>
                                                    </article>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- table-responsive// -->
                            </div>
                        </div>
                    </div>
                    <!-- card-body end// -->
                </div>
                <!-- card end// -->
            </section>
        {% endblock content %}

ecomprj/templates/useradmin/products.html
{% extends "useradmin/base.html" %}    
    {% load static %}
        {% block content %} 
            <section class="content-main">
                <div class="content-header">
                    <div>
                        <h2 class="content-title card-title">Products List</h2>
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                    <div>
                        <a href="{% url "useradmin:add-product" %}" class="btn btn-primary rounded"><i class="material-icons md-edit mr-10"></i>Create new</a>
                    </div>
                </div>
                <div class="card mb-4">
                    <header class="card-header">
                        <div class="row align-items-center">
                            <div class="col-md-2 col-6">
                                <select class="form-select">
                                    <option selected>Status</option>
                                    <option>Active</option>
                                    <option>Disabled</option>
                                    <option>Show all</option>
                                </select>
                            </div>
                        </div>
                    </header>
                    <!-- card-header end// -->
                    <div class="card-body">
                        {% for p in all_products %}
                        <article class="itemlist">
                            <div class="row align-items-center">
                                <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                                    <a class="itemside" href="#">
                                        <div class="left">
                                            <img src="{{p.image.url}}" class="img-sm img-thumbnail" alt="Item" />
                                        </div>
                                        <div class="info">
                                            <h6 class="mb-0">{{p.title|truncatechars:30}}</h6>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{p.price}}</span></div>
                                <div class="col-lg-2 col-sm-2 col-4 col-status">
                                    {% if p.status == True %}
                                    <span class="badge rounded-pill alert-success">Active</span>
                                    {% else %}
                                    <span class="badge rounded-pill alert-warning">Non-Active</span>
                                    {% endif %}
                                </div>
                                <div class="col-lg-1 col-sm-2 col-4 col-date">
                                    <span>{{p.date|date:"d M, Y"}}</span>
                                </div>
                                <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                                    <a href="{% url "useradmin:edit-product" p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                                    <a href="{% url "useradmin:delete-product" p.pid %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                                </div>
                            </div>
                            <!-- row .// -->
                        </article>
                        {% endfor %}
                        <!-- itemlist  .// -->
                    </div>
                    <!-- card-body end// -->
                </div>
                <!-- card end// -->
            </section>
{% endblock content %}