ecomprj/core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    # HOMEPAGE
    path('', views.index, name="index"),
    path("products/", views.product_list, name="product-list"),
    path("product/<pid>/", views.product_detail, name="product-detail"),

    # CATEGORY VIEW
    path("category/", views.category_list, name="category-list"),
    path("category/<cid>/", views.category_product_list, name="category-product-list"),

    # VENDOR VIEW
    path("vendors/", views.vendor_list, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail, name="vendor-detail"),

    #Tags
    path("product/tags/<slug:tag_slug>/",views.tag_list, name="tag-list"),

    #Review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    # SEARCH
    path("search/", views.search_view, name="search"),

    # Filter
    path("filter-products/", views.filter_products, name="filter-products"),

    #Add to Cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    #Cart List
    path("cart/", views.cart_view, name="cart"),
    #Delete from Cart
    path("delete-from-cart/", views.delete_from_cart_view, name="delete-from-cart"),
    #Update cart view
    path("update-cart/", views.update_cart_view, name="update-cart"),

    #CheckOut!
    path("checkout/<oid>/", views.checkout_view, name="checkout"),

    # #Paypal
    # path("paypal/", include('paypal.standard.ipn.urls'), name="paypal-ipn"),
    path("payment-successfull/<oid>/", views.payment_successfull, name="payment-successfull"),
    path("payment-failed/", views.payment_failed, name="payment-failed"),

    #Dashboard
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    #order detail
    path("dashboard/order/<int:id>/", views.order_products, name="order-detail"),

    #Make Default
    path("make-default-address/", views.make_default_address, name="make-default-address"),

    #Wishlist
    path("wishlist/", views.wishlist_view, name="wishlist"),

    #Add to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    #Remove from wishlist
    path("remove-from-wishlist/", views.remove_from_wishlist, name="remove-from-wishlist"),

    #Contact US
    path("contact-us/", views.contact_us, name="contact"),
    path("ajax-contact-us", views.ajax_contact_us, name="ajax_contact_us"),

    #new paths
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),
    path("api/create_checkout_session/<oid>/", views.create_checkout_session, name="create-checkout-session"),

    #About us
    path("about-us/", views.about_us, name="about-us"),

    #Purchase Guide
    path("purchase-guide/", views.purchase_guide, name="purchase-guide"),
    #Privacy Policy
    path("privacy-policy/", views.privacy_policy, name="privacy-policy"),
    #Terms of Services
    path("terms-of-service/", views.terms_of_service, name="terms-of-service"),
    ]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path("user/", include('userauths.urls', namespace='userauths')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
    path("useradmin/", include('useradmin.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/userauths/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_user, name="sign-up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/update/", views.profile_update, name="profile-update"),
    path("change-password/", views.change_password, name="change-password"),
    path("verify-email/", views.email_verification_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
    path('admin/password_reset/',auth_views.PasswordResetView.as_view(),name='admin_password_reset'),
    path('admin/password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

ecomprj/userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=50)
    bio = models.CharField(max_length=100)
    is_email_verified = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self) :
        return self.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", default="userimage.jpg")
    full_name = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=500, null=True, blank=True)
    phone = models.CharField(max_length=30, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    country = models.CharField(max_length=20, null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username
    
class ContactUs(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, default="XYZ@gmail.com")
    phone = models.CharField(max_length=50, default="+123 (456) 789")
    subject = models.CharField(max_length=50, default="Help!")
    message = models.TextField()

    def __str__(self) -> str:
        return self.full_name
    
    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_profile, sender = User)
post_save.connect(save_profile, sender = User)

ecomprj/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter your UserName", "class" : "form-group"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Bio Here!"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Your Password!"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Your Password"}))

    class Meta:
        model = User
        fields = ["username", "email", "bio"]

class ProfileUpdateForm(forms.ModelForm):

    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Phone"}))

    class Meta:
        model = Profile
        fields = ["full_name", "image", "bio", "phone"]

ecomprj/userauths/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from .models import User, Profile
from .forms import UserRegisterForm, ProfileUpdateForm
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, authenticate ,logout
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from .email import send_email_verification
from django.contrib.auth import get_user_model
from .utils import EmailVerificationTokenGenerator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str

User = get_user_model()

@csrf_exempt
def register_user(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, You Account was Created Successfully!")
            new_user = authenticate(username = form.cleaned_data["email"],
                         password = form.cleaned_data["password1"])
            login(request, new_user)
            return redirect("core:index")
    else:
        form = UserRegisterForm()
   
    context = {
      "form" : form,
      }
    return render(request, "userauths/sign-up.html", context)

@csrf_exempt
def login_view(request):
    if request.user.is_authenticated:
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email = email)
            
            user = authenticate(request, email = email, password = password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are successfully logged In!")
                return redirect("core:index")
            else:
                messages.error(request, "User doesn't exist, Please Sign-Up")

        except:
            messages.error(request, f"User with {email} doesn't exist")

    return render(request, "userauths/sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request,"Logged Out Successfully!")
    return redirect("userauths:login")

def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid:
            user_p = form.save(commit=False)
            user_p.user = request.user
            user_p.save()
            messages.success(request,"Profile Updated Successfully!")
            return redirect("core:dashboard")
    else:
            form = ProfileUpdateForm(instance=profile)
    context = {
        "form" : form,
        "profile" : profile,
    }
    return render(request,"userauths/profile-update.html", context)

@login_required
def change_password(request):
    user = request.user

    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        if new_password != confirm_password:
            messages.error(request, "Password Miss-Matched!!")
            return redirect("userauths:change-password")
        
        if check_password(old_password, user.password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password Changed Successfully")
            return redirect("userauths:login")
        else:
            messages.error(request, "Old Password is not correct")
            return redirect("userauths:change-password")
    return render(request, "userauths/change-password.html")

def email_verification_request(request):
    if not request.user.is_email_verified:
        send_email_verification(request, request.user.id)
        return HttpResponse("Email Verification link sent!")
    return HttpResponseForbidden("Email Already Verified!")

def email_verifier(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=uid)
        profile = Profile.objects.get(user=user)
    except:
        user = None
        profile = None

    if user == request.user:
        if EmailVerificationTokenGenerator.check_token(user, token):
            user.is_email_verified = True
            profile.verified = True
            user.save()
            profile.save()
            messages.success(request, "Profile Verified")
            return HttpResponseRedirect(reverse("userauths:profile-update"))
        return HttpResponseBadRequest("Invalid Request")
    
    return HttpResponseForbidden("You are not allowed to access this link")

ecomprj/templates/userauths/email-verify.html
{% autoescape off %}  
Hi {{ full_name }},  
Please click on the link to verfy your email,  
http://{{ domain }}{% url 'userauths:email-activate' uidb64=uid token=token %}  
{% endautoescape %}  

ecomprj/templates/userauths/profile-update.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url "core:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#profile"><i class="fas fa-user mr-10"></i>Profile</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url "userauths:logout" %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-3">Update Profile</h3>
                                            </div>
                                            {% if form.error %}
                                            <div class="alert alert-danger">
                                                <span>{{form.error}}</span>
                                            </div>
                                            {% endif %}
                                            <div class="card-body">
                                                <div class="container mt-5">
                                                    <div class="row justify-content-center">
                                                        <div class="col-md-8">
                                                            <div class="card shadow-lg">
                                                                <div class="card-body text-center">
                                                                    <div class="position-relative mb-3 mt-80">
                                                                        {% if profile.image %}
                                                                        <img src="{{profile.image.url}}" class="rounded-circle mb-3 img-thumbnail" alt="Profile Image" width="150" height="150">
                                                                        {% else %}
                                                                        <img src="https://www.shutterstock.com/image-vector/blank-avatar-photo-place-holder-600nw-1095249842.jpg" class="rounded-circle mb-3 img-thumbnail" alt="Profile Image" width="150" height="150">
                                                                        {% endif %}
                                                                    </div>
                                                                    <form action="" method="POST" enctype="multipart/form-data">
                                                                        {% csrf_token %}
                                                                        <div class="form-group">
                                                                            <label for="fullName" class="font-weight-bold">Full Name</label>
                                                                            {{form.full_name}}
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <label for="bio" class="font-weight-bold">Bio</label>
                                                                            {{form.bio}}
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <label for="bio" class="font-weight-bold">Phone</label>
                                                                            {{form.phone}}
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <label for="phone" class="font-weight-bold">Image</label>
                                                                            {{form.image}}
                                                                        </div>
                                                                        <button class="btn btn-primary position-absolute" type="submit" style="top: 10px; right: 10px;">
                                                                            <i class="fas fa-edit"></i> Edit
                                                                        </button>
                                                                        {% if request.user.is_email_verified %} 
                                                                            <div class="form-group">
                                                                                <label for="verified" class="font-weight-bold">Verified Status</label>
                                                                                <div>
                                                                                    {% if profile.verified %}
                                                                                        <i class="fas fa-check-circle text-success"></i> Verified
                                                                                    {% else %}
                                                                                        <i class="fas fa-times-circle text-danger"></i> Not Verified
                                                                                    {% endif %}
                                                                                </div>
                                                                            </div>
                                                                        {% else %}
                                                                            <a href="{% url "userauths:verify-email" %}" class="btn btn-primary position-absolute" type="submit" style="top: 10px; left: 10px;">
                                                                                Email Verification
                                                                            </a>
                                                                        {% endif %}
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>                                               
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

ecomprj/templates/userauths/sign-in.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url "userauths:sign-up" %}">Create here</a></p>
                                        </div>
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required name="email" placeholder="Username or Email *" />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="Your password *" />
                                            </div>
                                            {% comment %} <div class="login_footer form-group">
                                                <div class="chek-form">
                                                    <input type="text" required="" name="email" placeholder="Security code *" />
                                                </div>
                                                <span class="security-code">
                                                    <b class="text-new">8</b>
                                                    <b class="text-hot">6</b>
                                                    <b class="text-sale">7</b>
                                                    <b class="text-best">5</b>
                                                </span>
                                            </div> {% endcomment %}
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                                    </div>
                                                </div>
                                                <a class="text-muted" href="{% url "userauths:admin_password_reset" %}">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}